/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com;

import com.Library;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        new Library().someLibraryMethod();
    }
}
